from pydantic import BaseModel
from typing import List


class NormalizedSearchResult(BaseModel):
    title: str
    url: str


class SourceSection(BaseModel):
    title: str
    content: str
    url: str


class ResearchSection(BaseModel):
    subquestion: str
    sources: List[SourceSection]


class StructuredResearchOutput(BaseModel):
    original_query: str
    sections: List[ResearchSection]


"""
Final research output comes in the StructuredResearchOutput class
Putting all the classes together results in an output that looks like:

query: original user prompt
sections: a list of subquestions each with:
    subquestion: research questions generated by LLM agent
    sources: a list of sources that answer the subquestion, each with:
        title: title of the source
        content: the content of the web page
        url: URL of the web page
"""